server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.114.3.18:3306/mybatis?useUnicode=yes&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    database: 0
    host: 47.114.3.18
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
    thymeleaf:
      cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.boot.redis.entity